[package]
name = "dark_side_of_the_moon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
bevy_rapier2d = {version = "0.22", features = ["debug-render-2d"]}
rand = "0.8.5"
